METADATA = 'metadata'
CONTENT = 'content'
FILENAME = 'filename'

PARAM_CREATION_DATE = '_audit_creation_date'
PARAM_R1 = '_diffrn_reflns_av_R_equivalents'
PARAM_SIGMI_NETI = '_diffrn_reflns_av_sigmaI/netI'
PARAM_COMPLETENESS = '_reflns_odcompleteness_completeness'
PARAM_SPACEGROUP = '_space_group_name_H-M_alt'
PARAM_SPACEGROUP_NUM = '_space_group_IT_number'

PARAM_CONST_CELLA = '_cell_length_a'
PARAM_CONST_CELLB = '_cell_length_b'
PARAM_CONST_CELLC = '_cell_length_c'
PARAM_CONST_AL = '_cell_angle_alpha'
PARAM_CONST_BE = '_cell_angle_beta'
PARAM_CONST_GA = '_cell_angle_gamma'
PARAM_CONST_VOL = '_cell_volume'

PARAM_REFLECTIONS = '_cell_measurement_reflns_used'
PARAM_WAVELENGTH = '_diffrn_radiation_wavelength'

PARAM_CELLA = '_cell_oxdiff_length_a'
PARAM_CELLB = '_cell_oxdiff_length_b'
PARAM_CELLC = '_cell_oxdiff_length_c'
PARAM_AL = '_cell_oxdiff_angle_alpha'
PARAM_BE = '_cell_oxdiff_angle_beta'
PARAM_GA = '_cell_oxdiff_angle_gamma'
PARAM_VOL = '_cell_oxdiff_volume'

PARAM_UB11 = '_diffrn_orient_matrix_UB_11'
PARAM_UB12 = '_diffrn_orient_matrix_UB_12'
PARAM_UB13 = '_diffrn_orient_matrix_UB_13'
PARAM_UB21 = '_diffrn_orient_matrix_UB_21'
PARAM_UB22 = '_diffrn_orient_matrix_UB_22'
PARAM_UB23 = '_diffrn_orient_matrix_UB_23'
PARAM_UB31 = '_diffrn_orient_matrix_UB_31'
PARAM_UB32 = '_diffrn_orient_matrix_UB_32'
PARAM_UB33 = '_diffrn_orient_matrix_UB_33'

PARAM_2THETA_MIN = '_cell_measurement_theta_min'
PARAM_2THETA_MAX = '_cell_measurement_theta_max'
